"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "../..");
const read = p => fs.readFileSync(path.join(root, p), "utf8");
const controller = read("DiamDev.Give.UI/Controllers/BorradorNcController.cs");
const dal = read("DiamDev.Give.DAL/BorradorNcDashboardDA.cs");
const view = read("DiamDev.Give.UI/Views/BorradorNc/DetalleBorradorBNC.cshtml");
const dashboard = read("DiamDev.Give.UI/Views/BorradorNc/DashboardBNC.cshtml");
const sql = read("SqlMigrations/BorradoresNC/07_vincular_nc_borrador_seguro.sql");
const project = read("DiamDev.Give.UI/DiamDev.Give.UI.csproj");

assert.match(dashboard, /data-url-ver="@Url\.Action\("DetalleBorradorBNC", "BorradorNc"\)"/);
assert.match(dashboard, /<th class="bnc-sap-column">NC en SAP<\/th>/);
assert.doesNotMatch(dashboard, /<th[^>]*>NC del borrador<\/th>/);
assert.match(controller, /\[BorradorNcPermiso\(PERMISO_DASHBOARD\)\]\s+public ActionResult DetalleBorradorBNC/);
assert.match(controller, /public ActionResult DetalleBorradorBNC[\s\S]*?if \(!PuedeConsultarDashboard\(enc\)\) return new HttpUnauthorizedResult\(\);/);
assert.match(controller, /\[HttpPost\]\s+\[ValidateAntiForgeryToken\]\s+\[BorradorNcPermiso\(PERMISO_DASHBOARD\)\]\s+public ActionResult VincularNcBNC/);
assert.match(controller, /public ActionResult VincularNcBNC[\s\S]*?if \(!PuedeConsultarDashboard\(enc\)\) return new HttpUnauthorizedResult\(\);/);
assert.match(controller, /nc\.DocEntry != docEntry \|\| nc\.Cancelado/);
assert.match(controller, /x\.Clase == "NOTA_CREDITO"/);
assert.match(controller, /string\.Equals\(x\.CardCode, enc\.IdCliente/);
assert.match(controller, /enc\.Detalles\.Any\(d => string\.Equals\(d\.Documento, x\.Factura/);
assert.match(controller, /GroupBy\(x => x\.DocEntry\)/);
assert.match(controller, /DocEntry = x\.DocEntry/);
assert.match(dal, /IsolationLevel\.Serializable/);
assert.match(dal, /INSERT dbo\.BORR_NC_NC_VINCULO/);
assert.match(dal, /@docEntry.*SqlDbType\.Int/);
assert.match(sql, /IF DB_NAME\(\) <> N'POS-SmartK66'/);
assert.match(sql, /FOREIGN KEY \(ID_EMPRESA, ID_BORRADOR\)/);
assert.match(sql, /UNIQUE NONCLUSTERED \(ID_EMPRESA, DOC_ENTRY\)/);
assert.match(sql, /CHECK \(DOC_ENTRY > 0\)/);
assert.match(view, /name="codigoNc"/);
assert.match(view, /name="docEntry"/);
assert.match(view, /Confirmar vínculo/);
assert.match(view, /Facturas y productos/);
assert.match(view, /Documentación de respaldo/);
assert.match(view, /Actividad del borrador/);
assert.match(view, /Url\.Action\("Imprimir"/);
assert.match(view, /Url\.Action\("DetalleFacturaBorrador"/);
assert.match(view, /Url\.Action\("DetalleDocumentoPrevio"/);
assert.match(view, /Url\.Action\("DescargarAdjunto"/);
for (const file of ["Content\\borrador-nc-dashboard-detalle.css", "Scripts\\App\\BorradorNc-DashboardDetalle.js", "Views\\BorradorNc\\DetalleBorradorBNC.cshtml"])
    assert.ok(project.includes(file), "Falta en el proyecto: " + file);
console.log("OK: detalle individual, vínculo SAP validado, alcance, migración y publicación.");
