"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "../..");
const read = p => fs.readFileSync(path.join(root, p), "utf8");
const bll = read("DiamDev.Give.BLL/BorradorNcBLL.cs");
const dal = read("DiamDev.Give.DAL/BorradorNcDA.cs");
const hana = read("DiamDev.Give.DAL/HanaRepository.cs");
const controller = read("DiamDev.Give.UI/Controllers/BorradorNcController.cs");
const start = dal.indexOf("public void GuardarBorradorCompleto(");
assert.ok(start >= 0);
const creation = dal.slice(start, dal.indexOf("public bool", start));
assert.match(bll, /f\.Disponible = f\.DocTotal;/);
assert.doesNotMatch(bll, /TotalFactura - acumulado|DocTotal - f\.Acumulado|BloquearPorNcPrevia/);
assert.match(bll, /if \(d\.Importe > d\.TotalFactura\)/);
assert.match(bll, /Esto no impide crear este borrador/);
assert.match(bll, /facturas\.Where\(EsFacturaAbierta\)/);
assert.match(bll, /factura\.Pagado < factura\.DocTotal/);
assert.match(creation, /d\.Importe <= 0 \|\| d\.Importe > d\.TotalFactura/);
assert.doesNotMatch(creation, /sqlAcumulado|TotalFactura - acumulado/);
assert.match(creation, /cn\.BeginTransaction\(\)/);
assert.match(creation, /tx\.Commit\(\)/);
assert.match(read("SqlMigrations/BorradoresNC/01_crear_estructura_segura.sql"), /UNIQUE \(ID_EMPRESA, ID_BORRADOR, DOCUMENTO\)/);
assert.match(hana, /AND H\.\\"CANCELED\\" = 'N'/);
assert.match(hana, /lista\.GroupBy\(x => x\.DocEntry\)/);
assert.match(hana, /x\.Value\.GroupBy\(n => n\.DocEntry\)/);
assert.match(hana, /Cancelado = !string\.Equals\(LeerCampo\(row, "CANCELED"\), "N"/);
const endpoint = controller.slice(controller.indexOf("public ActionResult ObtenerIndicadoresSap"), controller.indexOf("public JsonResult ObtenerBitacoraBNC"));
assert.match(controller, /\[HttpPost\]\s*\[ValidateAntiForgeryToken\]\s*public ActionResult ObtenerIndicadoresSap/);
assert.match(endpoint, /unicas\.Count > 100/);
assert.match(endpoint, /origen == "seguimiento" \? PERMISO_VER/);
assert.match(endpoint, /origen == "autorizaciones" \? PERMISO_AUTORIZAR/);
assert.match(endpoint, /origen == "dashboard" \? PERMISO_DASHBOARD/);
assert.match(endpoint, /alcance\.Global \|\| propio/);
assert.match(endpoint, /enc\.EsPendiente/);
assert.ok(endpoint.indexOf("if (!permitido)") < endpoint.indexOf("_bll.ObtenerDocumentosPrevios"));
assert.match(endpoint, /BorradorNcBLL\.NotasCreditoDelBorrador\(enc, documentos\)/);
assert.match(bll, /string\.Equals\(x\.CardCode, enc\.IdCliente/);
assert.match(endpoint, /GroupBy\(x => x\.DocEntry\)/);
assert.match(endpoint, /NcVigentes = distintas\.Count\(x => !x\.Cancelado\)/);
assert.match(endpoint, /NcCanceladas = distintas\.Count\(x => x\.Cancelado\)/);
assert.match(endpoint, /Disponible = false/);
assert.match(dal, /public List<BorradorNcEncabezado> ObtenerParaIndicadores/);
const minimal = dal.slice(dal.indexOf("public List<BorradorNcEncabezado> ObtenerParaIndicadores"), dal.indexOf("public BorradorNcEncabezado ObtenerPorId"));
assert.match(minimal, /SqlDbType\.NVarChar, 15/);
assert.match(minimal, /SqlDbType\.NVarChar, 20/);
assert.doesNotMatch(minimal, /CONTENIDO|BORR_NC_ADJUNTO/);
for (const vista of ["Index", "Autorizaciones", "DashboardBNC"]) {
    const source = read("DiamDev.Give.UI/Views/BorradorNc/" + vista + ".cshtml");
    assert.match(source, /BorradorNc-SapIndicadores\.js/);
    assert.match(source, /data-url-sap-indicadores/);
    assert.match(source, /IntervaloConsultaSapSegundos/);
}
assert.match(read("DiamDev.Give.UI/Views/BorradorNc/DashboardBNC.cshtml"), /NC al crear \(histórico\)/);
assert.match(controller, /"NC al crear \(histórico\)"/);
console.log("OK: reutilización sin bloqueo acumulado, tope individual, NC deduplicadas y alcance de indicadores SAP.");
