//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamDev.Give.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliveryREntities : DbContext
    {
        public DeliveryREntities()
            : base("name=DeliveryREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<KpiDelivery_Result> KpiDelivery(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KpiDelivery_Result>("KpiDelivery", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_topclientes_Result> sp_topclientes(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_topclientes_Result>("sp_topclientes", fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_cuentaporcobrar_historico_Result> sp_cuentaporcobrar_historico(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cuentaporcobrar_historico_Result>("sp_cuentaporcobrar_historico", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_recibos_anulados_Result> sp_recibos_anulados(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_recibos_anulados_Result>("sp_recibos_anulados", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_ventas_despachadas_por_dia_Result> sp_ventas_despachadas_por_dia(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ventas_despachadas_por_dia_Result>("sp_ventas_despachadas_por_dia", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_despachosportransporte_fecha_Result> sp_despachosportransporte_fecha(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_despachosportransporte_fecha_Result>("sp_despachosportransporte_fecha", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_ventascomparativa_Result> sp_ventascomparativa(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ventascomparativa_Result>("sp_ventascomparativa", fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_ventasxvendedor_cons_Result> sp_ventasxvendedor_cons(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ventasxvendedor_cons_Result>("sp_ventasxvendedor_cons", fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_ventasxvendedor_cons_det_Result> sp_ventasxvendedor_cons_det(Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ventasxvendedor_cons_det_Result>("sp_ventasxvendedor_cons_det", fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<sp_ventasporproductotop_Result> sp_ventasporproductotop(Nullable<long> agencia, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var agenciaParameter = agencia.HasValue ?
                new ObjectParameter("Agencia", agencia) :
                new ObjectParameter("Agencia", typeof(long));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ventasporproductotop_Result>("sp_ventasporproductotop", agenciaParameter, fechaInicialParameter, fechaFinalParameter);
        }
    }
}
