/* CLIENTES CRM. Ejecutar solo tras revisar 00_diagnostico_previo.sql.
   La aplicación nunca crea ni modifica socios de negocio en SAP. */
USE [POS-SmartK66_DEV];
GO
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF DB_NAME() <> N'POS-SmartK66_DEV'
    THROW 55000, 'Base incorrecta para Clientes CRM.', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.CRM_CLIENTE', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CRM_CLIENTE
        (
            ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_CLIENTE PRIMARY KEY,
            NIT_CLAVE nvarchar(50) NOT NULL,
            RAZON_SOCIAL nvarchar(200) NOT NULL,
            NOMBRE_COMERCIAL nvarchar(200) NULL,
            ACTIVO bit NOT NULL CONSTRAINT DF_CRM_CLIENTE_ACTIVO DEFAULT (1),
            VERSION int NOT NULL CONSTRAINT DF_CRM_CLIENTE_VERSION DEFAULT (1),
            CREADO_POR nvarchar(100) NOT NULL,
            CREADO_EN datetime2(0) NOT NULL CONSTRAINT DF_CRM_CLIENTE_CREADO DEFAULT (SYSDATETIME()),
            ACTUALIZADO_POR nvarchar(100) NOT NULL,
            ACTUALIZADO_EN datetime2(0) NOT NULL CONSTRAINT DF_CRM_CLIENTE_ACTUALIZADO DEFAULT (SYSDATETIME())
        );
        CREATE UNIQUE INDEX UX_CRM_CLIENTE_NIT ON dbo.CRM_CLIENTE(NIT_CLAVE);
    END;

    IF OBJECT_ID(N'dbo.CRM_CLIENTE_EMPRESA', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CRM_CLIENTE_EMPRESA
        (
            CLIENTE_ID bigint NOT NULL,
            EMPRESA nvarchar(15) NOT NULL,
            CODIGO_SAP nvarchar(50) NULL,
            FICHA_JSON nvarchar(max) NOT NULL,
            ACTIVO bit NOT NULL CONSTRAINT DF_CRM_CE_ACTIVO DEFAULT (1),
            COMPRA_ACTUAL bit NOT NULL CONSTRAINT DF_CRM_CE_COMPRA DEFAULT (0),
            MONEDA nvarchar(3) NULL,
            VENTA_12M decimal(18,2) NULL,
            POTENCIAL_ANUAL decimal(18,2) NULL,
            OBJETIVO_12M decimal(18,2) NULL,
            VERSION int NOT NULL CONSTRAINT DF_CRM_CE_VERSION DEFAULT (1),
            ACTUALIZADO_POR nvarchar(100) NOT NULL,
            ACTUALIZADO_EN datetime2(0) NOT NULL CONSTRAINT DF_CRM_CE_ACTUALIZADO DEFAULT (SYSDATETIME()),
            CONSTRAINT PK_CRM_CLIENTE_EMPRESA PRIMARY KEY (CLIENTE_ID, EMPRESA),
            CONSTRAINT FK_CRM_CE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES dbo.CRM_CLIENTE(ID),
            CONSTRAINT CK_CRM_CE_EMPRESA CHECK (EMPRESA IN (N'BOLIK', N'FAES', N'GRACO'))
        );
        CREATE UNIQUE INDEX UX_CRM_CE_CODIGO_SAP
            ON dbo.CRM_CLIENTE_EMPRESA(EMPRESA, CODIGO_SAP)
            WHERE CODIGO_SAP IS NOT NULL;
        CREATE INDEX IX_CRM_CE_EMPRESA ON dbo.CRM_CLIENTE_EMPRESA(EMPRESA, ACTUALIZADO_EN DESC);
    END;

    IF OBJECT_ID(N'dbo.CRM_SOLICITUD', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CRM_SOLICITUD
        (
            ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_SOLICITUD PRIMARY KEY,
            CLIENTE_ID bigint NULL,
            EMPRESA nvarchar(15) NOT NULL,
            CODIGO_OPERADOR nvarchar(100) NOT NULL,
            AGENTE nvarchar(150) NOT NULL,
            RAZON_SOCIAL nvarchar(200) NOT NULL,
            NIT_CLAVE nvarchar(50) NOT NULL,
            ESTADO nvarchar(15) NOT NULL,
            FICHA_JSON nvarchar(max) NOT NULL,
            COMPRA_ACTUAL bit NOT NULL CONSTRAINT DF_CRM_SOL_COMPRA DEFAULT (0),
            MONEDA nvarchar(3) NULL,
            VENTA_12M decimal(18,2) NULL,
            POTENCIAL_ANUAL decimal(18,2) NULL,
            OBJETIVO_12M decimal(18,2) NULL,
            CREADO_POR nvarchar(100) NOT NULL,
            CREADO_EN datetime2(0) NOT NULL CONSTRAINT DF_CRM_SOL_CREADO DEFAULT (SYSDATETIME()),
            ENVIADO_EN datetime2(0) NULL,
            RESUELTO_EN datetime2(0) NULL,
            RESUELTO_POR nvarchar(100) NULL,
            MOTIVO_RECHAZO nvarchar(1000) NULL,
            VERSION int NOT NULL CONSTRAINT DF_CRM_SOL_VERSION DEFAULT (1),
            CONSTRAINT FK_CRM_SOL_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES dbo.CRM_CLIENTE(ID),
            CONSTRAINT CK_CRM_SOL_EMPRESA CHECK (EMPRESA IN (N'BOLIK', N'FAES', N'GRACO')),
            CONSTRAINT CK_CRM_SOL_ESTADO CHECK (ESTADO IN (N'BORRADOR', N'ENVIADA', N'APROBADA', N'RECHAZADA'))
        );
        CREATE INDEX IX_CRM_SOL_ESTADO ON dbo.CRM_SOLICITUD(EMPRESA, ESTADO, CREADO_EN DESC);
        CREATE INDEX IX_CRM_SOL_CREADOR ON dbo.CRM_SOLICITUD(CREADO_POR, CREADO_EN DESC);
        CREATE INDEX IX_CRM_SOL_NIT ON dbo.CRM_SOLICITUD(EMPRESA, NIT_CLAVE, ESTADO);
    END;

    IF OBJECT_ID(N'dbo.CRM_ARCHIVO', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CRM_ARCHIVO
        (
            ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_ARCHIVO PRIMARY KEY,
            SOLICITUD_ID bigint NULL,
            CLIENTE_ID bigint NULL,
            EMPRESA nvarchar(15) NOT NULL,
            TIPO nvarchar(30) NOT NULL,
            NOMBRE nvarchar(255) NOT NULL,
            CONTENT_TYPE nvarchar(100) NOT NULL,
            TAMANO int NOT NULL,
            CONTENIDO varbinary(max) NOT NULL,
            CREADO_POR nvarchar(100) NOT NULL,
            CREADO_EN datetime2(0) NOT NULL CONSTRAINT DF_CRM_ARCHIVO_CREADO DEFAULT (SYSDATETIME()),
            CONSTRAINT FK_CRM_ARCHIVO_SOL FOREIGN KEY (SOLICITUD_ID) REFERENCES dbo.CRM_SOLICITUD(ID),
            CONSTRAINT FK_CRM_ARCHIVO_CLI FOREIGN KEY (CLIENTE_ID) REFERENCES dbo.CRM_CLIENTE(ID),
            CONSTRAINT CK_CRM_ARCHIVO_OWNER CHECK
                ((SOLICITUD_ID IS NOT NULL AND CLIENTE_ID IS NULL) OR
                 (SOLICITUD_ID IS NULL AND CLIENTE_ID IS NOT NULL)),
            CONSTRAINT CK_CRM_ARCHIVO_TAMANO CHECK (TAMANO > 0 AND TAMANO <= 5242880)
        );
        CREATE INDEX IX_CRM_ARCHIVO_SOL ON dbo.CRM_ARCHIVO(SOLICITUD_ID, TIPO);
        CREATE INDEX IX_CRM_ARCHIVO_CLI ON dbo.CRM_ARCHIVO(CLIENTE_ID, TIPO);
    END;

    IF OBJECT_ID(N'dbo.CRM_AUDITORIA', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CRM_AUDITORIA
        (
            ID bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_AUDITORIA PRIMARY KEY,
            ENTIDAD nvarchar(30) NOT NULL,
            ENTIDAD_ID bigint NULL,
            EMPRESA nvarchar(15) NULL,
            USUARIO nvarchar(100) NOT NULL,
            ACCION nvarchar(50) NOT NULL,
            DETALLE nvarchar(max) NULL,
            ANTES_JSON nvarchar(max) NULL,
            DESPUES_JSON nvarchar(max) NULL,
            IP nvarchar(45) NULL,
            FECHA datetime2(0) NOT NULL CONSTRAINT DF_CRM_AUD_FECHA DEFAULT (SYSDATETIME())
        );
        CREATE INDEX IX_CRM_AUD_ENTIDAD ON dbo.CRM_AUDITORIA(ENTIDAD, ENTIDAD_ID, FECHA DESC);
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
