/* Solo lectura después de 05. */
USE [POS-SmartK66_DEV];
GO
SET NOCOUNT ON;
SELECT N'CONTRATO' AS SECCION,
       CASE WHEN OBJECT_ID(N'dbo.CRM_CLIENTE_USUARIO',N'U') IS NOT NULL
            THEN N'OK' ELSE N'FALTA' END AS TABLA_PROPIETARIOS,
       CASE WHEN EXISTS (SELECT 1 FROM dbo.Permiso
                         WHERE Nombre=N'Control.Clientes.CarteraGlobal')
            THEN N'OK' ELSE N'FALTA' END AS PERMISO_GLOBAL,
       CASE WHEN EXISTS (SELECT 1 FROM sys.indexes
                         WHERE object_id=OBJECT_ID(N'dbo.CRM_CLIENTE_USUARIO')
                           AND name=N'IX_CRM_CU_USUARIO')
            THEN N'OK' ELSE N'FALTA' END AS INDICE_PROPIETARIOS,
       (SELECT PermisoId FROM dbo.Menu WHERE Nombre=N'ClientesCartera') AS PERMISO_MENU;
SELECT N'VINCULOS' AS SECCION, ORIGEN, COUNT(*) AS TOTAL
FROM dbo.CRM_CLIENTE_USUARIO GROUP BY ORIGEN ORDER BY ORIGEN;
SELECT N'SIN_PROPIETARIO' AS SECCION,E.CLIENTE_ID,E.EMPRESA
FROM dbo.CRM_CLIENTE_EMPRESA E
WHERE NOT EXISTS (SELECT 1 FROM dbo.CRM_CLIENTE_USUARIO U
                  WHERE U.CLIENTE_ID=E.CLIENTE_ID AND U.EMPRESA=E.EMPRESA)
ORDER BY E.CLIENTE_ID,E.EMPRESA;
SELECT N'ROLES_GLOBALES' AS SECCION,R.Nombre
FROM dbo.Rol_Permiso RP JOIN dbo.Rol R ON R.Rol_Id=RP.Rol_Id
WHERE RP.Permiso_Id=N'Control.Clientes.CarteraGlobal'
ORDER BY R.Nombre;
GO
