// <auto-generated />
namespace DiamDev.Give.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActualizarFacturaColumnaNotaCredito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActualizarFacturaColumnaNotaCredito));
        
        string IMigrationMetadata.Id
        {
            get { return "201706260141334_ActualizarFacturaColumnaNotaCredito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
