// <auto-generated />
namespace DiamDev.Give.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeAgregoColumnaVistaAReparacionAnotacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeAgregoColumnaVistaAReparacionAnotacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201904041202154_SeAgregoColumnaVistaAReparacionAnotacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
